name: SplashScreenSample-SIT-CD

on:
  workflow_dispatch: # Manual Trigger
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy SIT Build
    needs: package
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build APK
        run: ./gradlew assembleSitDebug

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/sit/debug/app-sit-debug.apk \
            --app ${{ secrets.FIREBASE_APP_ID_SIT }}\
            --token "${{ secrets.FIREBASE_TOKEN }}"

